services:
  api:
    image: ghcr.io/mavel-x/proper_coffee_api:latest
    environment:
      - GEOAPIFY_API_KEY=${GEOAPIFY_API_KEY}
      - DB_URL=${DB_URL}
    restart: unless-stopped

  bots:
    image: ghcr.io/mavel-x/proper_coffee_bot:latest
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - API_URL=api/coffee/
    restart: unless-stopped
