version: '3.7'

services:
  api:
    image: mavelx/proper_coffee_api:latest
    environment:
      - GEO_API=${GEO_API}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-places}
    volumes:
      - ./container_data:/app/data
    restart: unless-stopped
    depends_on:
      - db

  bots:
    image: mavelx/proper_coffee_bot:latest
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - API_HOST=api
    restart: unless-stopped

  db:
    image: postgres:15.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-places}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
