name: CD

on:
  push:
    branches:
      - main

permissions:
  actions: read
  packages: write
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'api/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          cd api/
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/proper_coffee_api:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  bots:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'bots/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          cd bots/
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/proper_coffee_bot:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
