name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  api:
    runs-on: ubuntu-latest
    env:
      DB_TYPE: sqlite
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Path Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'api/**'

      - name: Set up Python
        if: steps.filter.outputs.api == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.filter.outputs.api == 'true'
        run: |
          cd api/
          pip install -r requirements.txt

      - name: Run tests
        if: steps.filter.outputs.api == 'true'
        run: |
          cd api/
          pytest
